spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      
  datasource:
    url: "jdbc:mysql://localhost:3306/ljelectrar"
    username: ljelectrar
    password: 123456789
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081